GET http://localhost:3000/cards
# gets and filters the card
####


GET http://localhost:3000/cards?power=3500&cardNumber=7
# gets and filters the card
####


POST http://localhost:3000/cards/create HTTP/1.1
content-type: application/json

{
    "id": 156,
    "name": "Sergio Castillo",
    "Cost": 200
}

# This will create a new card
####

POST http://localhost:3000/getToken
# This will create a new card
####

PUT http://localhost:3000/cards/:id
# edits cards
####

PUT http://localhost:3000/cards/155 HTTP/1.1
Content-Type: application/json

{
    "name": "Sergio Castillo",
    "Cost": 200
}

# edits cards
####

DELETE http://localhost:3000/cards/156

# deletes cards
####


DELETE http://localhost:3000/cards/:id
# deletes cards
####