GET http://localhost:3000/cards
# gets and filters the card
####

POST http://localhost:3000/cards/create HTTP/1.1
content-type: application/json

{
    "id": 155,
    "name": "vape God"
}

# This will create a new card
####

POST http://localhost:3000/getToken
# This will create a new card
####

PUT http://localhost:3000/cards/:id
# edits cards
####

PUT http://localhost:3000/cards/155 HTTP/1.1
Content-Type: application/json

{
    "name": "Vape Lord",
    "Cost": 200
}

# edits cards
####

DELETE http://localhost:3000/cards/155 HTTP/1.1
Content-Type: application/json

# deletes cards
####


DELETE http://localhost:3000/cards/:id
# deletes cards
####